# Generated by Django 6.0.1 on 2026-05-15 02:03

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "cliente_nome",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                (
                    "cliente_telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone do Cliente",
                    ),
                ),
                ("data_horario", models.DateTimeField(verbose_name="Data e Horário")),
                (
                    "duracao",
                    models.IntegerField(default=60, verbose_name="Duração (min)"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "finalizado",
                    models.BooleanField(default=False, verbose_name="Finalizado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aguardando", "Aguardando"),
                            ("Em Atendimento", "Em Atendimento"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data_horario"],
            },
        ),
    ]
