# Generated by Django 6.0.1 on 2026-05-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Serviço"
            ),
        ),
    ]
