# Generated by Django 6.0.1 on 2026-05-15 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_agendamento_servico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="servico",
        ),
    ]
