# Generated by Django 6.0.1 on 2026-09-02 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_remove_servico_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="profissional",
            field=models.ForeignKey(
                default="000000000000000000000000",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profissional",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["profissional", "data_horario"],
                name="agenda_agen_profiss_06b17e_idx",
            ),
        ),
    ]
